version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  node-app:
    build: .
    container_name: node-app
    depends_on:
      - kafka
    environment:
      - APP_PORT=3000
      - APP_HOST_IP=127.0.0.1
      - KAFKA_BROKER=localhost:9092
      - KAFKA_MAIN_TOPIC=kafka_streamer_topic
      - DOTENV_CONFIG_QUIET=true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]
